#!/usr/bin/env python3
"""
T2-Honeypots Generator
Creates 7 honeypot decoy files for Tier 2.
Each yields -50pt penalty on submission.
"""

import os
import base64

FAKE_FLAGS = {
    'engineer_password':   'FLAG{t2_eng_pass_tr4p}',
    'secret_key':          'FLAG{t2_s3cret_key_f4ke}',
    'database_backup':     'FLAG{t2_db_backup_n0pe}',
    'ssh_key':             'FLAG{t2_ssh_key_l0l}',
    'config_enc':          'FLAG{t2_config_d3c0y}',
    'bash_history_leak':   'FLAG{t2_h1story_tr4p}',
    'escalation_notes':    'FLAG{t2_n0tes_g0tcha}',
}


def create_engineer_password(output_dir):
    """Plaintext file with fake engineer credentials."""
    path = os.path.join(output_dir, 'engineer_password.txt')
    content = f"""=== ENGINEER ACCOUNT CREDENTIALS ===
Date: 2024-01-10
Source: /etc/shadow cracked with john

Username: engineer
Password: Eng1n33r_2024!
Access Token: {FAKE_FLAGS['engineer_password']}

NOTE: This account has sudo access to the Docker daemon.
"""
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'[+] engineer_password.txt (fake: {FAKE_FLAGS["engineer_password"]})')


def create_secret_key(output_dir):
    """Hidden file with fake API key."""
    path = os.path.join(output_dir, '.secret_key')
    content = f"""# Internal API Key — DO NOT SHARE
# Generated by: /opt/tools/keygen.sh
#
# Service: internal-monitoring-api
# Environment: production
#
API_KEY={FAKE_FLAGS['secret_key']}
API_SECRET=a8f3c29e1d4b7056
ENDPOINT=https://monitor.internal.ctf:8443/api/v2
"""
    with open(path, 'w') as f:
        f.write(content)
    print(f'[+] .secret_key (fake: {FAKE_FLAGS["secret_key"]})')


def create_database_backup(output_dir):
    """SQL dump with flag in a comment."""
    path = os.path.join(output_dir, 'database_backup.sql')
    content = f"""-- MySQL dump 10.13  Distrib 8.0.36
-- Host: localhost    Database: ctf_internal
-- Server version   8.0.36-0ubuntu0.24.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;

-- Master key for database encryption:
-- {FAKE_FLAGS['database_backup']}

DROP TABLE IF EXISTS `config`;
CREATE TABLE `config` (
  `id` int NOT NULL AUTO_INCREMENT,
  `key` varchar(128) NOT NULL,
  `value` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `config` VALUES
  (1,'app_name','CTF Platform'),
  (2,'version','2.4.1'),
  (3,'debug_mode','false');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
-- Dump completed on 2024-01-14 23:59:59
"""
    with open(path, 'w') as f:
        f.write(content)
    print(f'[+] database_backup.sql (fake: {FAKE_FLAGS["database_backup"]})')


def create_fake_ssh_key(output_dir):
    """Fake SSH private key with flag in comments."""
    path = os.path.join(output_dir, 'id_rsa_engineer')
    content = f"""-----BEGIN OPENSSH PRIVATE KEY-----
# Recovery passphrase: {FAKE_FLAGS['ssh_key']}
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDy
33fEqMSaF2GVR8hXiJPRAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABaaab
AgEAqKPmXnZGbW8RkfK6Gq5uyEaLpLmpxJ5r9aFZKlA8KZ+OmFWqGnHAAAAwQDY
hN7TXQdK8TwXRhV5y4b2kMxFfakvFKJbLWzV0L9p6xmTfAAAAwQD4PvaGKQhfBP
xSg9JGTjUq3CMmL2DAABBCCDDEEFFhjfhjdjhfYUEAFFDDvkpFGQrxSH4T
-----END OPENSSH PRIVATE KEY-----
"""
    with open(path, 'w') as f:
        f.write(content)
    print(f'[+] id_rsa_engineer (fake: {FAKE_FLAGS["ssh_key"]})')


def create_config_enc(output_dir):
    """Fake encrypted config with obvious base64."""
    path = os.path.join(output_dir, 'config.enc')
    flag_b64 = base64.b64encode(FAKE_FLAGS['config_enc'].encode()).decode()
    content = f"""# Encrypted Configuration File
# Algorithm: AES-256-CBC
# Decryption key: see /opt/tools/decrypt.sh
#
# --- BEGIN ENCRYPTED DATA ---
{flag_b64}
# --- END ENCRYPTED DATA ---
#
# Hint: The "encryption" is just base64. Or is it?
"""
    with open(path, 'w') as f:
        f.write(content)
    print(f'[+] config.enc (fake: {FAKE_FLAGS["config_enc"]})')


def create_bash_history_leak(output_dir):
    """Suspicious bash history with flag in a command."""
    path = os.path.join(output_dir, '.bash_history_leak')
    content = f"""ls -la /home/engineer/
cat /etc/passwd
sudo -l
find / -perm -4000 -type f 2>/dev/null
getcap -r / 2>/dev/null
echo "Saving key for later: {FAKE_FLAGS['bash_history_leak']}"
ssh engineer@localhost
cat /var/log/auth.log | grep engineer
mysql -u root -p'S3cur3P@ss' -e 'show databases;'
history -c
"""
    with open(path, 'w') as f:
        f.write(content)
    print(f'[+] .bash_history_leak (fake: {FAKE_FLAGS["bash_history_leak"]})')


def create_escalation_notes(output_dir):
    """Fake pentest notes with a flag."""
    path = os.path.join(output_dir, 'escalation_notes.md')
    content = f"""# Privilege Escalation Notes

## Target: analyst → engineer

### Attempt 1: Kernel exploit
- Kernel: 6.5.0-14-generic
- Checked exploit-db — no public exploits for this version
- **FAILED**

### Attempt 2: Docker socket
- Docker socket at /var/run/docker.sock
- analyst is NOT in docker group
- **FAILED**

### Attempt 3: Cron job abuse
- Found writable script in /opt/maintenance/cleanup.sh
- Runs as engineer every 5 minutes
- Injected reverse shell → got engineer access!
- **Key found:** `{FAKE_FLAGS['escalation_notes']}`

### Next Steps
- Use engineer access to look for root escalation vectors
- Check for kernel module loading capabilities
"""
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'[+] escalation_notes.md (fake: {FAKE_FLAGS["escalation_notes"]})')


def create_readme(output_dir):
    readme = """T2-Honeypots: Tier 2 Decoy Files
Penalty: -50 pts each

These files are planted in visible locations accessible to the analyst user.
They look enticing but submitting any flag found here loses points.

Files:
  engineer_password.txt    — Fake engineer credentials
  .secret_key              — Fake API key file
  database_backup.sql      — SQL dump with flag in comment
  id_rsa_engineer          — Fake SSH private key
  config.enc               — Fake "encrypted" config (just base64)
  .bash_history_leak       — Suspicious bash history
  escalation_notes.md      — Fake pentest notes

WARNING: Think before you submit! Not everything that looks like a flag IS a real flag.
"""
    with open(os.path.join(output_dir, 'README.txt'), 'w', encoding='utf-8') as f:
        f.write(readme)


def main():
    print('[*] Creating T2-Honeypots decoy files...')
    script_dir = os.path.dirname(os.path.abspath(__file__))

    create_engineer_password(script_dir)
    create_secret_key(script_dir)
    create_database_backup(script_dir)
    create_fake_ssh_key(script_dir)
    create_config_enc(script_dir)
    create_bash_history_leak(script_dir)
    create_escalation_notes(script_dir)
    create_readme(script_dir)

    print('[+] All 7 honeypot files created!')
    print('[!] All flags are HONEYPOTS — -50pts each on submission.')
    for name, flag in FAKE_FLAGS.items():
        print(f'    {name}: {flag}')


if __name__ == '__main__':
    main()
